//
//  CharacterDetailsInteractor.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 15/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsBusinessLogic
{
  func doSomething(request: CharacterDetails.Something.Request)
}

protocol CharacterDetailsDataStore
{
  //var name: String { get set }
}

class CharacterDetailsInteractor: CharacterDetailsBusinessLogic, CharacterDetailsDataStore
{
  var presenter: CharacterDetailsPresentationLogic?
  var worker: CharacterDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CharacterDetails.Something.Request)
  {
//    worker = CharacterDetailsWorker()
//    worker?.doSomeWork()
    
    let response = CharacterDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
