//
//  CharactersDetailsPresenterTests.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 27/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import desafio_ios_joni_campos
import XCTest

class CharactersDetailsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CharactersDetailsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCharactersDetailsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCharactersDetailsPresenter()
  {
    sut = CharactersDetailsPresenter()
  }
  
  // MARK: Test doubles
  
  class CharactersDetailsDisplayLogicSpy: CharactersDetailsDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: CharactersDetails.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = CharactersDetailsDisplayLogicSpy()
    sut.viewController = spy
    let response = CharactersDetails.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
