//
//  CharactersDetailsInteractorTests.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 27/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import desafio_ios_joni_campos
import XCTest

class CharactersDetailsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CharactersDetailsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCharactersDetailsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCharactersDetailsInteractor()
  {
    sut = CharactersDetailsInteractor()
  }
  
  // MARK: Test doubles
  
  class CharactersDetailsPresentationLogicSpy: CharactersDetailsPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: CharactersDetails.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = CharactersDetailsPresentationLogicSpy()
    sut.presenter = spy
    let request = CharactersDetails.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
