//
//  CharacterDetailsInteractorTests.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 29/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Personagens_Marvel
import XCTest

class CharacterDetailsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CharacterDetailsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCharacterDetailsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCharacterDetailsInteractor()
  {
    sut = CharacterDetailsInteractor()
  }
  
  // MARK: Test doubles
  
  class CharacterDetailsPresentationLogicSpy: CharacterDetailsPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: CharacterDetails.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = CharacterDetailsPresentationLogicSpy()
    sut.presenter = spy
    let request = CharacterDetails.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
