//
//  CharacterExpensiveComicPresenterTests.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 27/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import desafio_ios_joni_campos
import XCTest

class CharacterExpensiveComicPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: CharacterExpensiveComicPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupCharacterExpensiveComicPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupCharacterExpensiveComicPresenter()
  {
    sut = CharacterExpensiveComicPresenter()
  }
  
  // MARK: Test doubles
  
  class CharacterExpensiveComicDisplayLogicSpy: CharacterExpensiveComicDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: CharacterExpensiveComic.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = CharacterExpensiveComicDisplayLogicSpy()
    sut.viewController = spy
    let response = CharacterExpensiveComic.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
