//
//  ListCharactersInteractorTests.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 27/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import desafio_ios_joni_campos
import XCTest

class ListCharactersInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListCharactersInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListCharactersInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListCharactersInteractor()
  {
    sut = ListCharactersInteractor()
  }
  
  // MARK: Test doubles
  
  class ListCharactersPresentationLogicSpy: ListCharactersPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: ListCharacters.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ListCharactersPresentationLogicSpy()
    sut.presenter = spy
    let request = ListCharacters.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
