//
//  CharacterExpensiveComicPresenter.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 15/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterExpensiveComicPresentationLogic
{
    func presentSomething(response: CharacterExpensiveComic.Something.Response)
}

class CharacterExpensiveComicPresenter: CharacterExpensiveComicPresentationLogic
{
    weak var viewController: CharacterExpensiveComicDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CharacterExpensiveComic.Something.Response)
    {
        let viewModel = CharacterExpensiveComic.Something.ViewModel(oExpensive: response)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
