//
//  CharacterExpensiveComicRouter.swift
//  desafio-ios-joni-campos
//
//  Created by Joni de Campos on 15/04/20.
//  Copyright (c) 2020 Joni de Campos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharacterExpensiveComicRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CharacterExpensiveComicDataPassing
{
  var dataStore: CharacterExpensiveComicDataStore? { get }
}

class CharacterExpensiveComicRouter: NSObject, CharacterExpensiveComicRoutingLogic, CharacterExpensiveComicDataPassing
{
  weak var viewController: CharacterExpensiveComicViewController?
  var dataStore: CharacterExpensiveComicDataStore?
  
  
}
